# 语言设置
language: zh_CN
# 存储方式, 可选: YAML, MYSQL 默认 YAML
save-option:
  type: YAML
  # MySQL的URL，例如jdbc:mysql://127.0.0.1/minecraft 格式：jdbc:mysql://MySQL地址/数据库名
  url: jdbc:mysql://localhost/minecraft
  # 数据库用户名
  user: "root"
  # 数据库密码
  password: "root"
# 是否启用加入战斗取消, 如果无卡战斗bug, 推荐不开启
JoinEndBattle: false
# 模块开关
enable: true
# 是否开启异步, 推荐为 false, 卡服可设置为 true, 但存在复制的可能性.
async: false
# 兑换冷却, 如果是 MySQL, 越低越卡服, 20 = 1s
convert-delay: 60
# 精灵信息物品
Item:
  name: "&b%pokemon_name%"
  shiny:
    enable: true
    header: ""
  lore:
    - "&f"
    - "&a ▶ &b等级: &f%Level% "
    - "&a ▶ &b个体信息&f(&e进度: &f%IVS_SUM%&f)"
    - "&f  ▪ &a血量:&f %IVS_HP% &a攻击:&f %IVS_Attack%"
    - "&f  ▪ &a速度:&f %IVS_Speed% &a防御:&f %IVS_Defence%"
    - "&f  ▪ &a特攻:&f %IVS_SpecialAttack% &a特防:&f %IVS_SpecialDefence%"
    - "&a ▶ &b努力值信息&f(&e进度: &f%EVS_SUM%&f)"
    - "&f  ▪ &a血量:&f %EVS_HP% &a攻击:&f %EVS_Attack%"
    - "&f  ▪ &a速度:&f %EVS_Speed% &a防御:&f %EVS_Defence%"
    - "&f  ▪ &a特攻:&f %EVS_SpecialAttack% &a特防:&f %EVS_SpecialDefence%"
    - "&a ▶ &b基础信息:"
    - "&f  ▪ &a闪光: &f%Shiny%"
    - "&f  ▪ &a特性: &f%Ability%"
    - "&f  ▪ &a性格: &f%Nature%"
    - "&f  ▪ &a体型: &f%Growth%"
    - "&f  ▪ &a性别: &f%Gender%"
    - "&f  ▪ &a昵称: &f%Nick_Name%"
    - "&a ▶ &b技能信息:"
    - "&f  ▪ &a一技能: &f%Move1%"
    - "&f  ▪ &a二技能: &f%Move2%"
    - "&f  ▪ &a三技能: &f%Move3%"
    - "&f  ▪ &a四技能: &f%Move4%"
    - ""
    - "&a ▶ &b左键展示该精灵"
    - "&a ▶ &b右键转换成相片"
    - ""
  info:
    - "&f"
    - "&a ▶ &b等级: &f%Level% "
    - "&a ▶ &b个体信息&f(&e进度: &f%IVS_SUM%&f)"
    - "&f  ▪ &a血量:&f %IVS_HP% &a攻击:&f %IVS_Attack%"
    - "&f  ▪ &a速度:&f %IVS_Speed% &a防御:&f %IVS_Defence%"
    - "&f  ▪ &a特攻:&f %IVS_SpecialAttack% &a特防:&f %IVS_SpecialDefence%"
    - "&a ▶ &b努力值信息&f(&e进度: &f%EVS_SUM%&f)"
    - "&f  ▪ &a血量:&f %EVS_HP% &a攻击:&f %EVS_Attack%"
    - "&f  ▪ &a速度:&f %EVS_Speed% &a防御:&f %EVS_Defence%"
    - "&f  ▪ &a特攻:&f %EVS_SpecialAttack% &a特防:&f %EVS_SpecialDefence%"
    - "&a ▶ &b基础信息:"
    - "&f  ▪ &a闪光: &f%Shiny%"
    - "&f  ▪ &a特性: &f%Ability%"
    - "&f  ▪ &a性格: &f%Nature%"
    - "&f  ▪ &a体型: &f%Growth%"
    - "&f  ▪ &a性别: &f%Gender%"
    - "&f  ▪ &a昵称: &f%Nick_Name%"
    - "&a ▶ &b技能信息:"
    - "&f  ▪ &a一技能: &f%Move1%"
    - "&f  ▪ &a二技能: &f%Move2%"
    - "&f  ▪ &a三技能: &f%Move3%"
    - "&f  ▪ &a四技能: &f%Move4%"
    - ""
# 无精灵时展示
Fail:
  type: BARRIER
  name: "&c无精灵"