# 语言文件
language: zh_CN
# 是否开启 debug 模式
debug: false
# 存储方式, 可选: [ YAML, MySQL, SQLite ] 默认 YAML
save-option:
  type: YAML
  # MySQL的URL，例如 jdbc:mysql://127.0.0.1/minecraft 格式：jdbc:mysql://MySQL地址/数据库名
  url: jdbc:mysql://localhost/minecraft
  # 数据库用户名
  user: "root"
  # 数据库密码
  password: "root"

settings:
  # 是否启用转换模块
  convert: true